GET http://localhost:3000/api/animals
Accept: application/json
###

POST http://localhost:3000/api/animals/1/feed
Accept: application/json

###
POST https://shrew-square-vastly.ngrok-free.app/api/animals/1/feed
Accept: application/json


