GET http://localhost:3000/bidzina/status
Accept: application/json

### Update Pig Status to HAPPY
POST http://localhost:3000/bidzina/status
Content-Type: application/json

{
  "status": "happy"
}

### Update Pig Status to PUTIN
POST http://localhost:3000/bidzina/status
Content-Type: application/json

{
  "status": "putin"
}

### Update Pig Status to DEFAULT
POST http://localhost:3000/bidzina/status
Content-Type: application/json

{
  "status": "default"
}

